[package]
name = "kenchiku-scaffold"
version.workspace = true
edition.workspace = true

[dependencies]
eyre.workspace = true
tracing.workspace = true
mlua = { version = "0.11.5", features = ["lua54", "vendored", "send"] }

[dev-dependencies]
tempfile = "3"
