[package]
name = "kenchiku-scaffold"
version.workspace = true
edition.workspace = true

[dependencies]
kenchiku-lua.workspace = true
kenchiku-common.workspace = true

eyre.workspace = true
tracing.workspace = true
mlua.workspace = true
tempfile.workspace = true
serde.workspace = true
