[package]
name = "kenchiku-lua"
version.workspace = true
edition.workspace = true

[dependencies]
kenchiku-common.workspace = true

eyre.workspace = true
mlua.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
